"""Initial VMS Schema

Revision ID: 214a33dbde6b
Revises: 
Create Date: 2026-08-13 13:04:24.571642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '214a33dbde6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('RECRUITER', 'VENDOR_USER', 'SYSTEM')", name='chk_audit_event_actor_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=False),
    sa.Column('current_company', sa.String(length=255), nullable=False),
    sa.Column('total_experience', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('relevant_experience', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('notice_period', sa.String(length=50), nullable=False),
    sa.Column('ctc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ectc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=False),
    sa.Column('preferred_location', sa.String(length=255), nullable=False),
    sa.Column('pan_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('pan_encrypted', sa.Text(), nullable=False),
    sa.Column('linkedin_url', sa.String(length=255), nullable=False),
    sa.Column('education', sa.String(length=255), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_pan_fingerprint'), 'candidates', ['pan_fingerprint'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='chk_department_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('export_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=555), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internal_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('access_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("access_level IN ('STANDARD', 'ADMIN')", name='chk_internal_user_access_level'),
    sa.CheckConstraint("role = 'RECRUITER'", name='chk_internal_user_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name='chk_internal_user_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE UNIQUE INDEX uq_internal_users_lower_email ON internal_users (LOWER(email));")
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_normalized_name'), 'vendors', ['normalized_name'], unique=True)
    op.create_table('job_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'ACTIVE', 'CLOSED', 'ARCHIVED')", name='chk_job_role_status'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiter_signup_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_user_id', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED')", name='chk_recruiter_signup_status'),
    sa.ForeignKeyConstraint(['created_user_id'], ['internal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['internal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_signup_requests_email'), 'recruiter_signup_requests', ['email'], unique=False)
    op.create_table('vendor_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name='chk_vendor_user_status'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE UNIQUE INDEX uq_vendor_users_lower_email ON vendor_users (LOWER(email));")
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('vendor_user_id', sa.UUID(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'vendor_user_id', name='uq_idempotency_key_vendor_user')
    )
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('vendor_user_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=555), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('upload_state', sa.String(length=50), nullable=False),
    sa.Column('validation_state', sa.String(length=50), nullable=False),
    sa.Column('malware_scan_state', sa.String(length=50), nullable=False),
    sa.Column('processing_state', sa.String(length=50), nullable=False),
    sa.Column('eligibility_state', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("eligibility_state IN ('PENDING', 'ELIGIBLE', 'INELIGIBLE')", name='chk_resume_eligibility_state'),
    sa.CheckConstraint("malware_scan_state IN ('PENDING', 'CLEAN', 'INFECTED')", name='chk_resume_malware_scan_state'),
    sa.CheckConstraint("processing_state IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')", name='chk_resume_processing_state'),
    sa.CheckConstraint("upload_state IN ('PENDING', 'COMPLETED', 'FAILED')", name='chk_resume_upload_state'),
    sa.CheckConstraint("validation_state IN ('PENDING', 'VALID', 'INVALID')", name='chk_resume_validation_state'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('internal_user_id', sa.UUID(), nullable=True),
    sa.Column('vendor_user_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'REVOKED', 'EXPIRED')", name='chk_session_status'),
    sa.CheckConstraint('(internal_user_id IS NOT NULL) OR (vendor_user_id IS NOT NULL)', name='chk_session_user_presence'),
    sa.ForeignKeyConstraint(['internal_user_id'], ['internal_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('vendor_user_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cv_sent_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('employment_mode', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("employment_mode IN ('Perm', 'C2H')", name='chk_submission_employment_mode'),
    sa.CheckConstraint("status IN ('SUBMITTED', 'SCREENING', 'INTERVIEW', 'SELECTED', 'ONBOARDED', 'REJECTED')", name='chk_submission_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['job_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_signup_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_company_name', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('vendor_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED')", name='chk_vendor_signup_status'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['internal_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_signup_requests_email'), 'vendor_signup_requests', ['email'], unique=False)
    op.create_index(op.f('ix_vendor_signup_requests_normalized_company_name'), 'vendor_signup_requests', ['normalized_company_name'], unique=False)
    op.create_table('resume_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id')
    )
    op.create_table('status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('SUBMITTED', 'SCREENING', 'INTERVIEW', 'SELECTED', 'ONBOARDED', 'REJECTED')", name='chk_status_history_status'),
    sa.ForeignKeyConstraint(['changed_by'], ['internal_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Custom triggers & partial unique indexes
    op.execute("""
        CREATE OR REPLACE FUNCTION check_active_admins_limit()
        RETURNS TRIGGER AS $$
        DECLARE
            admin_count INTEGER;
        BEGIN
            IF (NEW.role = 'RECRUITER' AND NEW.access_level = 'ADMIN' AND NEW.status = 'ACTIVE') AND
               (TG_OP = 'INSERT' OR (TG_OP = 'UPDATE' AND (OLD.access_level != 'ADMIN' OR OLD.status != 'ACTIVE'))) THEN
                
                PERFORM pg_advisory_xact_lock(987654321);
                
                SELECT COUNT(*) INTO admin_count FROM internal_users 
                WHERE role = 'RECRUITER' AND access_level = 'ADMIN' AND status = 'ACTIVE';
                
                IF admin_count >= 2 THEN
                    RAISE EXCEPTION 'Maximum limit of 2 ACTIVE ADMIN Recruiters has been reached.';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_check_active_admins_limit
        BEFORE INSERT OR UPDATE ON internal_users
        FOR EACH ROW EXECUTE FUNCTION check_active_admins_limit();
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION make_status_history_immutable()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'status_history table is immutable and cannot be updated or deleted.';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_status_history_immutable
        BEFORE UPDATE OR DELETE ON status_history
        FOR EACH ROW EXECUTE FUNCTION make_status_history_immutable();
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION make_audit_events_immutable()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events table is immutable and cannot be updated or deleted.';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_events_immutable
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION make_audit_events_immutable();
    """)

    # Create partial unique indexes
    op.execute("CREATE UNIQUE INDEX uq_pending_recruiter_signup ON recruiter_signup_requests (email) WHERE status = 'PENDING';")
    op.execute("CREATE UNIQUE INDEX uq_pending_vendor_signup_email ON vendor_signup_requests (email) WHERE status = 'PENDING';")
    op.execute("CREATE UNIQUE INDEX uq_pending_vendor_signup_company ON vendor_signup_requests (normalized_company_name) WHERE status = 'PENDING';")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop partial unique indexes
    op.execute("DROP INDEX IF EXISTS uq_pending_vendor_signup_company;")
    op.execute("DROP INDEX IF EXISTS uq_pending_vendor_signup_email;")
    op.execute("DROP INDEX IF EXISTS uq_pending_recruiter_signup;")

    # Drop triggers and functions
    op.execute("DROP TRIGGER IF EXISTS trg_audit_events_immutable ON audit_events;")
    op.execute("DROP FUNCTION IF EXISTS make_audit_events_immutable();")
    op.execute("DROP TRIGGER IF EXISTS trg_status_history_immutable ON status_history;")
    op.execute("DROP FUNCTION IF EXISTS make_status_history_immutable();")
    op.execute("DROP TRIGGER IF EXISTS trg_check_active_admins_limit ON internal_users;")
    op.execute("DROP FUNCTION IF EXISTS check_active_admins_limit();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_history')
    op.drop_table('resume_extractions')
    op.drop_index(op.f('ix_vendor_signup_requests_normalized_company_name'), table_name='vendor_signup_requests')
    op.drop_index(op.f('ix_vendor_signup_requests_email'), table_name='vendor_signup_requests')
    op.drop_table('vendor_signup_requests')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('resumes')
    op.drop_table('idempotency_records')
    op.execute("DROP INDEX IF EXISTS uq_vendor_users_lower_email;")
    op.drop_table('vendor_users')
    op.drop_index(op.f('ix_recruiter_signup_requests_email'), table_name='recruiter_signup_requests')
    op.drop_table('recruiter_signup_requests')
    op.drop_table('job_roles')
    op.drop_index(op.f('ix_vendors_normalized_name'), table_name='vendors')
    op.drop_table('vendors')
    op.execute("DROP INDEX IF EXISTS uq_internal_users_lower_email;")
    op.drop_table('internal_users')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_candidates_pan_fingerprint'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
