"""add_recruiter_company_access

Revision ID: 229380eb06aa
Revises: 5e8a1490c94f
Create Date: 2026-08-22 16:59:32.980108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '229380eb06aa'
down_revision: Union[str, Sequence[str], None] = '5e8a1490c94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiter_company_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['internal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recruiter_id', 'company_id', name='uq_recruiter_company_access')
    )
    op.create_index(op.f('ix_recruiter_company_access_company_id'), 'recruiter_company_access', ['company_id'], unique=False)
    op.create_index(op.f('ix_recruiter_company_access_recruiter_id'), 'recruiter_company_access', ['recruiter_id'], unique=False)
    op.add_column('recruiter_signup_requests', sa.Column('requested_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiter_signup_requests', 'requested_companies')
    op.drop_index(op.f('ix_recruiter_company_access_recruiter_id'), table_name='recruiter_company_access')
    op.drop_index(op.f('ix_recruiter_company_access_company_id'), table_name='recruiter_company_access')
    op.drop_table('recruiter_company_access')
    # ### end Alembic commands ###
