"""add password reset tokens table

Revision ID: 79c8b2687259
Revises: 214a33dbde6b
Create Date: 2026-08-15 14:44:21.294810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c8b2687259'
down_revision: Union[str, Sequence[str], None] = '214a33dbde6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('internal_user_id', sa.UUID(), nullable=True),
    sa.Column('vendor_user_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(internal_user_id IS NOT NULL AND vendor_user_id IS NULL) OR (internal_user_id IS NULL AND vendor_user_id IS NOT NULL)', name='chk_password_reset_token_user_presence'),
    sa.ForeignKeyConstraint(['internal_user_id'], ['internal_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
